#Practice2.6 Square without corners
import turtle
turtle.setup(600,600,300,300)
turtle.penup()
turtle.seth(-90)
turtle.fd(250)
turtle.seth(-180)
turtle.fd(150)
turtle.pendown()
turtle.pensize(5)
turtle.pencolor("black")
turtle.seth(0)
for i in range(90,450,90):#range(开始值, 结束值, 步长)
    turtle.penup()
    turtle.fd(70)
    turtle.pendown()
    turtle.fd(200)
    turtle.penup()
    turtle.fd(70)
    turtle.seth(i)
